import discord
from discord.ext import commands
from discord import app_commands
import os
import asyncio
from dotenv import load_dotenv
import ai_database as database
import intelligence
import random
import string

load_dotenv()
TOKEN = os.getenv("NOVA_AI_TOKEN")

class NovaBot(commands.Bot):
    def __init__(self):
        intents = discord.Intents.default()
        intents.message_content = True
        intents.members = True
        super().__init__(command_prefix='!', intents=intents)

    async def setup_hook(self):
        await self.tree.sync()
        print("Nova AI Slash Commands Synced.")

bot = NovaBot()

@bot.event
async def on_ready():
    print(f"Nova GPT is online. Logged in as {bot.user}")
    # Add a debug key for the owner
    database.db.add_debug_key("NOVA-FREE-BETA")

@bot.event
async def on_message(message):
    # Only respond to DMs
    if message.author.bot: return
    
    if isinstance(message.channel, discord.DMChannel):
        if not database.db.is_authorized(str(message.author.id)):
            await message.channel.send("🔒 **Access Restricted.** You must redeem a license key to use Nova GPT.\nUse `/redeem <key>` in a shared server.")
            return

        async with message.channel.typing():
            response = await intelligence.engine.get_response(message.content, message.author.id)
            # Handle long responses (Discord 2000 char limit)
            if len(response) > 2000:
                for i in range(0, len(response), 2000):
                    await message.channel.send(response[i:i+2000])
            else:
                await message.channel.send(response)
    
    await bot.process_commands(message)

@bot.tree.command(name="redeem", description="Unlock Nova GPT for your DMs")
async def redeem(interaction: discord.Interaction, key: str):
    success = database.db.redeem_key(key, str(interaction.user.id))
    if success:
        embed = discord.Embed(title="✅ Access Granted", description="Nova GPT has been unlocked for your DMs. You can now chat with me directly!", color=discord.Color.green())
        await interaction.response.send_message(embed=embed, ephemeral=True)
    else:
        await interaction.response.send_message("❌ Invalid or already redeemed key.", ephemeral=True)

@bot.tree.command(name="status", description="Check your Nova GPT status")
async def status(interaction: discord.Interaction):
    authorized = database.db.is_authorized(str(interaction.user.id))
    status_text = "Authorized (Pro)" if authorized else "Unauthorized (Locked)"
    await interaction.response.send_message(f"**Nova GPT Status:** `{status_text}`", ephemeral=True)

@bot.tree.command(name="gen_key", description="Generate an AI license key (Staff Only)")
@app_commands.describe(duration="The duration of the license")
@app_commands.choices(duration=[
    app_commands.Choice(name="1 Day", value="1day"),
    app_commands.Choice(name="1 Week", value="1week"),
    app_commands.Choice(name="1 Month", value="1month"),
    app_commands.Choice(name="1 Year", value="1year"),
    app_commands.Choice(name="Lifetime", value="lifetime")
])
async def gen_key(interaction: discord.Interaction, duration: str):
    # Role check: "Chair of Government" or higher
    staff_role_name = "Chair of Government"
    has_permission = False
    
    if interaction.guild:
        # Check if user has the role or any role above it
        staff_role = discord.utils.get(interaction.guild.roles, name=staff_role_name)
        if staff_role:
            if interaction.user.top_role >= staff_role:
                has_permission = True
        elif interaction.user.guild_permissions.administrator:
            has_permission = True # Admins can always gen
    
    if not has_permission:
        await interaction.response.send_message("❌ You do not have permission to use this command.", ephemeral=True)
        return

    # Generate key
    key = f"NOVA-{''.join(random.choices(string.ascii_uppercase + string.digits, k=4))}-{''.join(random.choices(string.ascii_uppercase + string.digits, k=4))}-{''.join(random.choices(string.ascii_uppercase + string.digits, k=4))}"
    
    database.db.add_ai_license(key, duration)
    
    embed = discord.Embed(title="🔑 Key Generated", color=discord.Color.blue())
    embed.add_field(name="Key", value=f"`{key}`", inline=False)
    embed.add_field(name="Duration", value=duration.capitalize(), inline=True)
    embed.set_footer(text=f"Generated by {interaction.user}")
    
    await interaction.response.send_message(embed=embed)

if __name__ == "__main__":
    if TOKEN:
        bot.run(TOKEN)
    else:
        print("ERROR: NOVA_AI_TOKEN missing in .env")
